name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Ensure logs directory exists
        run: mkdir -p susi/logs
      - name: Run tests
        run: |
          pytest
      # Optionally build Docker image
      - name: Build Docker image
        run: docker build -t social-media-susi .